### ISSUE TITLE
Show.html

### ISSUE THREAD

**Issue by sproutecks2125** [offtherailspod/offtherailspod.github.io#10]
Add link and castbox icon/img to body for listeners to go to castbox and subscribe and comment. Castbox holds the analytics for show listens.

**Comment by mattweidner** [comment]
Unfortunately bootstrap doesn't have a castbox glyph icon to match the facebook, github, and twitter icons we are using. What do you think about changing the Listen menu option to Castbox, and the Show Notes menu option to Listen & Show Notes?

**Comment by sproutecks2125** [comment]
Image would work its more for a direct link to the cask box show page for comments and subscriptions. We could place it below the emedded sound tracks. With a link that says subscribe for all the shows.

**Comment by sproutecks2125** [comment]
We can change show notes The Show and i like the castbox idea.

**Comment by sproutecks2125** [comment]
Archives in show notes could got to a single page with the old links to former news articles. At the bottom of the code there is a section that could work perfect for this. We would have to modify a little bit though.

**Comment by mattweidner** [comment]
So what did we decide to do with this issue? I see a couple of different suggestions. I can take care of it, just want to make sure I'm making the right change.

**Comment by sproutecks2125** [comment]
We can close this issue. We've changed the direction and it no longer applies.
