### ISSUE TITLE
Comment page or script

### ISSUE THREAD

**Issue by sproutecks2125** [offtherailspod/offtherailspod.github.io#11]
Add a comments section for vistors to leave us comments.

**Comment by offtherailspod** [comment]
Perhaps the easiest way to accomplish this is to make a "Comments" link that takes them to the Contact Us page?

-Matt

**Comment by sproutecks2125** [comment]
I was thinking more for a comments section in page. But its not exactly necessary since we have the contact us section.

**Comment by mattweidner** [comment]
We could look at a third-party service like disqus.com. It should be fairly easy to integrate.

**Comment by mattweidner** [comment]
Added disqus comment service to show.html https://github.com/offtherailspod/offtherailspod.github.io/commit/2239de09aa23359b14192d37e056416b7bb78ffc
