### ISSUE TITLE
Adjust index.html text size

### ISSUE THREAD

**Issue by mattweidner** [offtherailspod/offtherailspod.github.io#2]
Some of the text size on the index.html page is too small. Brandon, please correct me if I'm wrong but the section "An informal, educational look..." is too small?

**Comment by sproutecks2125** [comment]
Correct. Would like the Font to change and possibly color. I just used Yellow to stand out. But the text in that paragraph is too small to read out.

**Comment by mattweidner** [comment]
Closing, as I like what you have done with the SecondPageLayout branch.
